### ISSUE TITLE
Question: Any documentation for setup/installation

### ISSUE THREAD

**Issue by cjagus** [bookingcom/carbonapi#124]
Also does this solve https://github.com/go-graphite/carbonapi/issues/186? . 

thanks in advance.

**Comment by grzkv** [comment]
Hi, @cjagus! Re setup. You could start with *docker-compose*, documented [here](https://github.com/bookingcom/carbonapi#run) and then replicate it to VMs or bare metal.

**Comment by azhiltsov** [comment]
That issue is quite old and our code had moved forward quite a bit. 
From the current state of product I see multiple issues in there and I don't really know which is really bugging you. I could spend some time and get in details about it, but I would rather ask you to describe your problem here, so I would be answering to your questions.

**Comment by cjagus** [comment]
@azhiltsov this one >
```
carbonapi currently assume that all Metrics for the function will have same resolution, if they don't - it won't extrapolate or interpolate them as graphite-web do, and that likely causes your panic to appear. It's a long known issue
```
FYI : https://github.com/go-graphite/carbonapi/issues/315#issuecomment-475991945

**Comment by azhiltsov** [comment]
This statement is still valid. We aware that this can cause issues and have plans to fix this later, another ticket about that is #75
We are tracking this in logs currently, you can look how often this happening by searching for lines 'metrics with differing resolution'
The issue with mismatched resolution might have different roots. 
- query might initially contain metrics with mismatched resolutions. Solution will be approximation based on consolidateBy (if specified) or xFilesFactor and aggregationMethod (if not)
- query might be targeting metrics with the same resolution but timeframe at the edge of whisper archives, where delay in execution of it might lead the result to be fetched from a different whisper archives. I can't come up with solution for this, but workaround is quite easy - avoid querying timeframes close to the edge, or configure your whispers to be a bit away from standard drop-down values. 
Use 1s:25h instead of 1s:24h or 1m:15d instead of 1m:14d
