### ISSUE TITLE
carbonapi doesn't build with cairo 1.16 on mac

### ISSUE THREAD

**Issue by gksinghjsr** [bookingcom/carbonapi#90]
Steps to reproduce:-
1. Brew latest cairo version
2. Try and build carbonapi, and it fails
3. If commit ff3e8c26849cb80ccadae6bb567e39bf7307b90a is reverted, it builds with the latest version.

**Comment by gksinghjsr** [comment]
cc @lomik

**Comment by lomik** [comment]
What error does the compiler print? I have version 1.16.0 and compile without errors

**Comment by grzkv** [comment]
Let me double-check this on my Mac as well.

**Comment by grzkv** [comment]
The problem is that the option `--with-X11` was removed from the new versions of `cairo` for *Mac*. Because of this, the libs are not available anymore at path `/opt/X11/lib` on *Mac*. This is why the build fails.

@lomik In my opinion, this is unrelated to your commit. This is due to `cairo` brew formula changes.

**Comment by grzkv** [comment]
Looks like the problem stems from cleaning and removing the old version of `xquartz` when updating `cairo`.

When everything is run cleanly, everything works with the new version.
